using UnityEngine;
using UnityEngine.UI;
using System;
using System.Collections.Generic;

namespace TowerUI
{
    /// <summary>
    /// Lightweight runtime component for binding to prefabs generated by TowerPrefabCompiler.
    /// Caches named nodes on Awake and provides typed accessors for common operations.
    /// Unlike TowerUIRenderer, this does NOT parse JSON or create nodes — the prefab already
    /// contains the full UGUI hierarchy.
    /// </summary>
    public class TowerUIBinder : MonoBehaviour
    {
        private Dictionary<string, GameObject> _nodes;

        public Action<string> onButtonClick;
        public Action<string, bool> onToggleChanged;
        public Action<string, float> onSliderChanged;
        public Action<string, string> onInputChanged;
        public Action<string, string> onInputSubmit;

        void Awake()
        {
            _nodes = new Dictionary<string, GameObject>();
            CacheNodes(transform);
        }

        private void CacheNodes(Transform parent)
        {
            for (int i = 0; i < parent.childCount; i++)
            {
                var child = parent.GetChild(i);
                string name = child.gameObject.name;
                if (!string.IsNullOrEmpty(name) && name != "TowerUI_Root")
                    _nodes[name] = child.gameObject;
                CacheNodes(child);
            }
        }

        public GameObject FindNode(string name)
        {
            if (_nodes == null) return null;
            _nodes.TryGetValue(name, out var go);
            return go;
        }

        public void SetText(string nodeName, string text)
        {
            var go = FindNode(nodeName);
            if (go == null) return;

            var label = go.transform.Find("Label");
            if (label != null)
                UIBridge.SetText(label.gameObject, text);
            else
                UIBridge.SetText(go, text);
        }

        public string GetText(string nodeName)
        {
            var go = FindNode(nodeName);
            if (go == null) return null;

            var tmp = go.GetComponent<TMPro.TextMeshProUGUI>();
            if (tmp != null) return tmp.text;

            var label = go.transform.Find("Label");
            if (label != null)
            {
                var tmpLabel = label.GetComponent<TMPro.TextMeshProUGUI>();
                if (tmpLabel != null) return tmpLabel.text;
            }

            var legacy = go.GetComponent<Text>();
            if (legacy != null) return legacy.text;

            return null;
        }

        public void SetColor(string nodeName, Color color)
        {
            var go = FindNode(nodeName);
            if (go == null) return;
            var img = go.GetComponent<Image>();
            if (img != null) { img.color = color; return; }
            UIBridge.SetTextColor(go, color.r, color.g, color.b, color.a);
        }

        public void SetVisible(string nodeName, bool visible)
        {
            var go = FindNode(nodeName);
            if (go != null) go.SetActive(visible);
        }

        public void SetOpacity(string nodeName, float alpha)
        {
            var go = FindNode(nodeName);
            if (go == null) return;
            var cg = UIBridge.EnsureCanvasGroup(go);
            cg.alpha = Mathf.Clamp01(alpha);
        }

        public Button GetButton(string nodeName)
        {
            var go = FindNode(nodeName);
            return go != null ? go.GetComponent<Button>() : null;
        }

        public void BindButton(string nodeName, UnityEngine.Events.UnityAction action)
        {
            var btn = GetButton(nodeName);
            if (btn != null) btn.onClick.AddListener(action);
        }

        public void BindAllButtons()
        {
            if (_nodes == null || onButtonClick == null) return;
            foreach (var kvp in _nodes)
            {
                var btn = kvp.Value.GetComponent<Button>();
                if (btn != null)
                {
                    string name = kvp.Key;
                    btn.onClick.AddListener(() =>
                    {
                        try { onButtonClick?.Invoke(name); }
                        catch (Exception e) { Debug.LogError($"[TowerBinder] Button '{name}' error: {e.Message}"); }
                    });
                }
            }
        }

        public void BindToggle(string nodeName, UnityEngine.Events.UnityAction<bool> action)
        {
            var toggle = GetToggle(nodeName);
            if (toggle != null) toggle.onValueChanged.AddListener(action);
        }

        public void BindSlider(string nodeName, UnityEngine.Events.UnityAction<float> action)
        {
            var slider = GetSlider(nodeName);
            if (slider != null) slider.onValueChanged.AddListener(action);
        }

        public void BindInput(string nodeName, UnityEngine.Events.UnityAction<string> onChange = null, UnityEngine.Events.UnityAction<string> onSubmit = null)
        {
            var go = FindNode(nodeName);
            if (go == null) return;
            var tmpInput = go.GetComponent<TMPro.TMP_InputField>();
            if (tmpInput != null)
            {
                if (onChange != null) tmpInput.onValueChanged.AddListener(onChange);
                if (onSubmit != null) tmpInput.onEndEdit.AddListener(onSubmit);
                return;
            }
            var legacyInput = go.GetComponent<InputField>();
            if (legacyInput != null)
            {
                if (onChange != null) legacyInput.onValueChanged.AddListener(onChange);
                if (onSubmit != null) legacyInput.onEndEdit.AddListener(onSubmit);
            }
        }

        public TMPro.TMP_InputField GetTMPInput(string nodeName)
        {
            var go = FindNode(nodeName);
            return go != null ? go.GetComponent<TMPro.TMP_InputField>() : null;
        }

        public InputField GetLegacyInput(string nodeName)
        {
            var go = FindNode(nodeName);
            return go != null ? go.GetComponent<InputField>() : null;
        }

        public void BindAll()
        {
            if (_nodes == null) return;
            foreach (var kvp in _nodes)
            {
                string name = kvp.Key;
                var go = kvp.Value;

                var btn = go.GetComponent<Button>();
                if (btn != null && onButtonClick != null)
                {
                    string n = name;
                    btn.onClick.AddListener(() =>
                    {
                        try { onButtonClick?.Invoke(n); }
                        catch (Exception e) { Debug.LogError($"[TowerBinder] Button '{n}' error: {e.Message}"); }
                    });
                }

                var toggle = go.GetComponent<Toggle>();
                if (toggle != null && onToggleChanged != null)
                {
                    string n = name;
                    toggle.onValueChanged.AddListener(val =>
                    {
                        try { onToggleChanged?.Invoke(n, val); }
                        catch (Exception e) { Debug.LogError($"[TowerBinder] Toggle '{n}' error: {e.Message}"); }
                    });
                }

                var slider = go.GetComponent<Slider>();
                if (slider != null && onSliderChanged != null)
                {
                    string n = name;
                    slider.onValueChanged.AddListener(val =>
                    {
                        try { onSliderChanged?.Invoke(n, val); }
                        catch (Exception e) { Debug.LogError($"[TowerBinder] Slider '{n}' error: {e.Message}"); }
                    });
                }

                var tmpInput = go.GetComponent<TMPro.TMP_InputField>();
                if (tmpInput != null)
                {
                    string n = name;
                    if (onInputChanged != null)
                        tmpInput.onValueChanged.AddListener(val =>
                        {
                            try { onInputChanged?.Invoke(n, val); }
                            catch (Exception e) { Debug.LogError($"[TowerBinder] Input '{n}' error: {e.Message}"); }
                        });
                    if (onInputSubmit != null)
                        tmpInput.onEndEdit.AddListener(val =>
                        {
                            try { onInputSubmit?.Invoke(n, val); }
                            catch (Exception e) { Debug.LogError($"[TowerBinder] Input '{n}' error: {e.Message}"); }
                        });
                }
            }
        }

        public Toggle GetToggle(string nodeName)
        {
            var go = FindNode(nodeName);
            return go != null ? go.GetComponent<Toggle>() : null;
        }

        public Slider GetSlider(string nodeName)
        {
            var go = FindNode(nodeName);
            return go != null ? go.GetComponent<Slider>() : null;
        }

        public string GetInputText(string nodeName)
        {
            var go = FindNode(nodeName);
            if (go == null) return null;
            return UIBridge.GetInputText(go);
        }

        public void SetInputText(string nodeName, string text)
        {
            var go = FindNode(nodeName);
            if (go != null) UIBridge.SetInputText(go, text);
        }

        public void SetSprite(string nodeName, Sprite sprite)
        {
            var go = FindNode(nodeName);
            if (go == null) return;
            var img = go.GetComponent<Image>();
            if (img != null) img.sprite = sprite;
        }

        public void SetSliderValue(string nodeName, float value)
        {
            var slider = GetSlider(nodeName);
            if (slider != null) slider.value = value;
        }

        public void SetToggleValue(string nodeName, bool value)
        {
            var toggle = GetToggle(nodeName);
            if (toggle != null) toggle.isOn = value;
        }

        public int NodeCount => _nodes?.Count ?? 0;

        public IEnumerable<string> NodeNames => _nodes?.Keys;
    }
}
